// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainingTrackerApi.Data;

#nullable disable

namespace TrainingTrackerApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrainingTrackerApi.Models.LiftEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Exercise")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<int>("Sets")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrainingWeekId")
                        .HasColumnType("int");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TrainingWeekId");

                    b.ToTable("LiftEntries");
                });

            modelBuilder.Entity("TrainingTrackerApi.Models.NutritionEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<int?>("CarbsGrams")
                        .HasColumnType("int");

                    b.Property<int?>("FatGrams")
                        .HasColumnType("int");

                    b.Property<int?>("ProteinGrams")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrainingWeekId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainingWeekId");

                    b.ToTable("NutritionEntries");
                });

            modelBuilder.Entity("TrainingTrackerApi.Models.TrainingWeek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("WeekStart")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TrainingWeeks");
                });

            modelBuilder.Entity("TrainingTrackerApi.Models.LiftEntry", b =>
                {
                    b.HasOne("TrainingTrackerApi.Models.TrainingWeek", "TrainingWeek")
                        .WithMany("LiftEntries")
                        .HasForeignKey("TrainingWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingWeek");
                });

            modelBuilder.Entity("TrainingTrackerApi.Models.NutritionEntry", b =>
                {
                    b.HasOne("TrainingTrackerApi.Models.TrainingWeek", "TrainingWeek")
                        .WithMany("NutritionEntries")
                        .HasForeignKey("TrainingWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingWeek");
                });

            modelBuilder.Entity("TrainingTrackerApi.Models.TrainingWeek", b =>
                {
                    b.Navigation("LiftEntries");

                    b.Navigation("NutritionEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
